//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUTO_GRADE
    {
        public int PRGR_CD_ID { get; set; }
        public int PROD_CD_ID { get; set; }
        public string PRGR_NM_COR { get; set; }
        public string PRGR_NM_TAMANHO { get; set; }
        public int PRGR_QN_QUANTIDADE { get; set; }
        public int PRGR_IN_ATIVO { get; set; }
        public Nullable<int> TAMA_CD_ID { get; set; }
    
        public virtual PRODUTO PRODUTO { get; set; }
    }
}
